### ISSUE TITLE
Purpose of the `--hold-period` option

### ISSUE THREAD

**Issue by matteocarnelos** [brgl/libgpiod#98]
The `gpioset` v2.1.3 [manpage](https://manpages.debian.org/experimental/gpiod/gpioset.1.en.html) states that:
> The line output state is maintained until the process exits, but after that is not guaranteed.

Therefore, what's the purpose and use-case of the `--hold-period` option?

The README mentions the following example as a use-case:
```
gpioset --hold-period 20ms -t0 GPIO23=1
```
But, can't the same behavior be achieved with the `--toggle` option?
```
gpioset --t20ms,0 GPIO23=1
```

**Comment by warthog618** [comment]
There are other cases where gpioset toggle lines and so the hold period applies, e.g. --interactive mode.
The user can dump a bunch of "toggle" commands to that and it will toggle at a rate determined by the hold period - without the user having to be concerned about timings when they issue the toggle.

It can also be used to set the minimum toggle period for a --toggle sequence, so you can change it in the one place rather than having to change everywhere in the sequence.

I'm really don't see your problem here.  If you can't see a use for it then don't use it?
